[package]
name = "pathway"
version = "0.1.0"
edition = "2021"
publish = false
rust-version = "1.69"

[lib]
name = "pathway_engine"
crate-type = ["cdylib", "lib"]

[dev-dependencies]
assert_matches = "1.5.0"
color-eyre = { version = "0.6.2", default-features = false }
eyre = "0.6.8"
tempfile = "3.6.0"

[dependencies]
arc-swap = "1.6.0"
arcstr = { version = "1.1.5", default-features = false, features = ["serde", "std"] }
base32 = "0.4.0"
bincode = "1.3.3"
cfg-if = "1.0.0"
chrono = { version = "0.4.26", features = ["std", "clock"], default-features = false }
chrono-tz = "0.8.3"
crossbeam-channel = "0.5.8"
csv = "1.2.2"
derivative = "2.2.0"
differential-dataflow = { path = "../../third_party/timely/differential-dataflow" }
elasticsearch = "8.5.0-alpha.1"
futures = "0.3.28"
hyper = { version = "0.14", features = ["server"] }
id-arena = "2.2.1"
itertools = "0.11.0"
jemallocator = { version = "0.5.0", features = ["stats", "disable_initial_exec_tls"] }
log = { version = "0.4.19", features = ["std"] }
ndarray = { version = "0.15.6", features = ["serde"] }
nix = { version = "0.26.2", default-features = false, features = ["fs"] }
num-integer = "0.1.45"
numpy = "0.18.0"
once_cell = "1.18.0"
ordered-float = { version = "3.7.0", features = ["serde"] }
pipe = "0.4.0"
postgres = "0.19.5"
prometheus-client = "0.21.2"
pyo3 = { version = "0.18.3", features = ["abi3-py38"] }
pyo3-asyncio = "0.18.0" 
pyo3-log = "0.8.2"
rand = "0.8.5"
rdkafka = { version = "0.33.2", features = ["ssl-vendored", "cmake-build"] }
rust-s3 = { version = "0.33.0", features = ["sync-native-tls-vendored", "sync-native-tls", "fail-on-err"], default-features = false }
scopeguard = "1.1.0"
send_wrapper = "0.6.0"
serde = { version = "1.0.171", features = ["derive", "rc"] }
serde_json = "1.0"
smallvec = { version = "1.11.0", features = ["union", "const_generics"] }
thiserror = "1.0.43"
timely = { path = "../../third_party/timely/timely-dataflow/timely", features = ["bincode"] }
tokio = "1.29.1"
typed-arena = "2.0.2"
xxhash-rust = { version = "0.8.6", features = ["xxh3"] }

[target.'cfg(target_os = "linux")'.dependencies]
inotify = "0.10.1"

[features]
unlimited-workers = []

# Helpful for using external memory profilers
standard-allocator = []

# YOLO!
yolo-id64 = []
yolo-id32 = []

[profile.dev]
opt-level = 3

[profile.profiling]
inherits = "release"
debug = true

[build-dependencies]
pyo3-build-config = "0.18.3"
