name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
# assignees:
#   - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  # - type: input
  #   id: contact
  #   attributes:
  #     label: Contact Details
  #     description: How can we get in touch with you if we need more info?
  #     placeholder: ex. email@example.com
  #   validations:
  #     required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What happened?
      placeholder: Tell us what you see! <br> It would be nice if you could leave us the logs.
      value: A bug description.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      placeholder: Tell us what you see!
      render: shell
    validations:
      required: true
  - type: textarea
    id: what-did-you-expect
    attributes:
      label: What did you expect to happen?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you want to see!
      value: Describe your expectations.
    validations:
      required: true
  - type: dropdown
    id: os_version
    attributes:
      label: Version
      description: On which OS version did you run Pathway?
      options:
        - Linux
        - MacOS
    validations:
      required: true
  - type: dropdown
    id: cpu_architecture
    attributes:
      label: On which CPU architecture did you run Pathway?
      multiple: true
      options:
        - x86_64
        - arm64
        - aarch64
  # - type: checkboxes
  #   id: terms
  #   attributes:
  #     label: Code of Conduct
  #     description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
  #     options:
  #       - label: I agree to follow this project's Code of Conduct
  #         required: true
