blank_issues_enabled: false
contact_links:
  - name: Questions & Help Github Discussions
    url: https://github.com/pathwaycom/pathway/discussions
    about: Discuss ideas for new features or enhancements
  - name: Questions & Help Discord
    url: https://discord.com/invite/pathway
    about: Please ask and answer questions here.
